apiVersion: monitoring.example.com/v1
kind: Notifier
metadata:
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/managed-by: kustomize
  name: notifier-sample
spec:
  # TODO(user): Add fields here
