apiVersion: monitoring.example.com/v1
kind: Notifier
metadata:
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/managed-by: kustomize
  name: notifier-sample
spec:
  channel: slack
  # List of namespaces to monitor
  namespaces:
    - default
    - kube-system

  # Event types to watch (e.g., Normal, Warning)
  eventTypes:
    - Warning

  # Specific event reasons to notify about
  eventReasons:
    - ImagePullFailed
    - CrashLoopBackOff
    - OOMKilled
    - FailedScheduling

  # Slack webhook URL where notifications should be sent
  webhook: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"

  # Optional default settings
  defaultSettings:
    messagePrefix: "[K8s Alert] "

